name: 'Build Go from source'
description: 'Build and test Go from source code'
inputs:
  go_variables:
    description: 'Variables and their values ready for export'
    required: false
  test_build:
    description: 'When set to true, all tests of build are executed'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Clone master of go
      shell: bash
      run: git clone --depth=1 --branch master --single-branch --no-tags https://go.googlesource.com/go

    - name: Apply patch files
      shell: bash
      run: |
        if [ ! -f *.patch ]; then echo "No patch file found. Skipping."; exit 0; fi
        export commitTitle=$(ls *.patch | head -1 | xargs -I {} basename {} .patch)
        mv *.patch ./go/src/
        cd go/src
        git config user.email "${{ github.event.pusher.email }}"
        git config user.name "${{ github.event.pusher.name }}"
        git apply -v --ignore-space-change --ignore-whitespace --whitespace=fix *.patch
        rm ./*.patch
        git add -A
        git commit -m $commitTitle
        git show -1 --stat

    - name: Build
      shell: bash
      run: |
        cd go/src
        export ${{ inputs.go_variables }}
        if [ -z "$GOROOT_BOOTSTRAP" ]; then export GOROOT_BOOTSTRAP=$(go env GOROOT); fi
        ./make.bash --no-banner
        ../bin/go version
    - name: Test
      shell: bash
      if: ${{ inputs.test_build == 'true' }}
      run: |
        cd go/src
        ./run.bash --no-rebuild

branding:
  icon: crosshair
  color: blue
